---
- name: Register to Red Hat account
  shell: subscription-manager register --username=mod-genesis-matzov --password=Aa1234567  --force

- name: Configure important repos
  shell: |
    subscription-manager repos --enable=rhel-8-for-x86_64-baseos-rpms &&
    subscription-manager repos --enable=rhel-8-for-x86_64-appstream-rpms &&
    dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
