- name: Stop NetworkManager service
  service:
    name: NetworkManager
    enabled: false
    state: stopped

- name: Configure dns server
  copy:
    content: nameserver 52.22.204.22
    dest: /etc/resolv.conf