- name: Set DNS server
  ansible.builtin.nmcli:
    conn_name: "{{ connection_name }}"
    type: ethernet
    dns4: "52.22.204.22"
    state: present
    dns4_ignore_auto: true
    notify:
      - restart NetworkManager
