---
- name: Install VirtualBox prerequisites
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@development"
    - kernel-devel
    - kernel-headers
    - dkms

- name: Download and Install VirtualBox
  get_url:
    url: https://download.virtualbox.org/virtualbox/6.1.30/VirtualBox-6.1-6.1.30_148432_el8-1.x86_64.rpm
    dest: /tmp/VirtualBox.rpm

- name: Install VirtualBox
  dnf:
    name: /tmp/VirtualBox.rpm
    state: present
    disable_gpg_check: true