---
- name: create dir
  ansible.builtin.file:
    path: /share
    state: directory
    mode: '0777'

- name: mount share
  ansible.posix.mount:
    path: /share
    src: "192.168.20.73:/share"
    state: mounted
    fstype: nfs

    #- name: unmount broken
    #ansible.posix.mount:
    #path: /mnt/share
    #src: "192.168.20.69:/share"
    #state: absent
    #fstype: nfs
